#!/usr/bin/python2.7

import hashlib

# User format -- name:shell:pass:salt:home
NAME = 0
SHELL = 1
HASH = 2
SALT = 3
HOME = 4

def hash(passwd, name, salt):
    return hashlib.sha1(name + salt + passwd)

def test(passwd, user):
    return hash(passwd, user[NAME], user[SALT]) == user[HASH]

def save(passwd, user = None, name = None, shell = None, home = None):
    if user is None:
        user = [name, shell, None, None, home]
    user[SALT] = hashlib.gensalt()
    user[HASH] = hash(passwd, user[NAME], user[SALT])

    return user
