#!/usr/bin/env python2

class SocketFileSystem(object):
	def __init__(self):
		self.data = {}
	
	def keys(self):
		return self.data.keys()

	def values(self):
		return self.data.values()

	def __getattr__(self, name):
		return getattr(self.data, name)

	def __getitem__(self, name):
		return self.data[name].pop()
	
	def __setitem__(self, name, value):
		if name in self.data.keys():
			self.data[name].append(value)
		else:
			self.data[name] = [value]

	def __delitem__(self, name):
		del self.data[name]

class FIFOFileSystem(SocketFileSystem):
	def __getitem__(self, name):
		return self.data[name].pop(0)
	
	def __setitem__(self, name, value):
		if name in self.data.keys():
			self.data[name].insert(0, value)
		else:
			self.data[name] = [value]

def bootstrap():
	set_path("/proc/stdin", SocketFileSystem())
	set_path("/proc/stdout", SocketFileSystem())
	set_path("/proc/stderr", SocketFileSystem())
	set_path("/proc/socket", SocketFileSystem())

def cleanup():
	set_path("/proc", {})
