#!/usr/bin/env python2

class FIFOFileSystem(object):
	def __init__(self):
		self.data = {}
	
	def keys(self):
		return self.data.keys()

	def values(self):
		return self.data.values()

	def __getattr__(self, name):
		return getattr(self.data, name)

	def __getitem__(self, name):
		return self.data[name].pop(0)
	
	def __setitem__(self, name, value):
		if name in self.data.keys():
			self.data[name].insert(0, value)
		else:
			self.data[name] = [value]

	def __delitem__(self, name):
		del self.data[name]

def bootstrap():
	set_path("/proc/stdin", FIFOFileSystem())
	set_path("/proc/stdout", FIFOFileSystem())
	set_path("/proc/stderr", FIFOFileSystem())
	set_path("/proc/socket", FIFOFileSystem())

def cleanup():
	set_path("/proc", {})
