#!/usr/bin/python2.7

while True:
    input = ""
    while not input.endswith("\n"):
        char = __files__["stdin"]
        if char:
            __files__["stdout"] = char
            input += char
    exec input[:-1]
